sudo: false
language: cpp

compiler:
  - gcc

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - cmake
    - cmake-curses-gui
    - make
    - libexpat1-dev
    - zlib1g-dev
    - libbz2-dev
    - libsparsehash-dev
    - libboost-dev
    - libboost-program-options-dev
    - libgdal-dev
    - libgeos++-dev
    - libproj-dev
    - doxygen
    - graphviz

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

before_script:
  - cd $HOME
  - git clone https://github.com/osmcode/libosmium
  - cd build/DisyInformationssysteme/osmotron
  - mkdir -p bin
  - cmake -version
  - cmake -D OSMIUM_INCLUDE_DIRS=$HOME/home/libosmium/include $HOME/build/DisyInformationssysteme/osmotron

script:
  - make
  - cd bin
  - ./testrunner